/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GarageIndexRouteImport } from './routes/garage/index'
import { Route as GarageCarIdRouteImport } from './routes/garage/$carId'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageIndexRoute = GarageIndexRouteImport.update({
  id: '/garage/',
  path: '/garage/',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageCarIdRoute = GarageCarIdRouteImport.update({
  id: '/garage/$carId',
  path: '/garage/$carId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/garage/$carId': typeof GarageCarIdRoute
  '/garage': typeof GarageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/garage/$carId': typeof GarageCarIdRoute
  '/garage': typeof GarageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/garage/$carId': typeof GarageCarIdRoute
  '/garage/': typeof GarageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/garage/$carId' | '/garage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/garage/$carId' | '/garage'
  id: '__root__' | '/' | '/about' | '/garage/$carId' | '/garage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  GarageCarIdRoute: typeof GarageCarIdRoute
  GarageIndexRoute: typeof GarageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage/': {
      id: '/garage/'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage/$carId': {
      id: '/garage/$carId'
      path: '/garage/$carId'
      fullPath: '/garage/$carId'
      preLoaderRoute: typeof GarageCarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  GarageCarIdRoute: GarageCarIdRoute,
  GarageIndexRoute: GarageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
